esphome:
  name: $devicename
  platform: ESP32
  board: nodemcu-32s


ota:
  password: "xxxxx"

wifi:
  ssid: "xxxxx"
  password: "xxxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
#  ap:
#    ssid: "Esp-Sensor Fallback Hotspot"
#    password: "xxxxx"

# captive_portal:


# Enable logging
logger:
  #level: VERY_VERBOSE
# Enable Home Assistant API
uart:
  - id: uart_1
    tx_pin: 18
    rx_pin: 19
    baud_rate: 9600
  - id: uart_2
    rx_pin: 26
    baud_rate: 9600  
i2c:
  sda: 23
  scl: 22
  scan: true
  id: bus_a
switch:
  - platform: gpio
    pin: 
      number: 27
    id: pms_set

# Enable Home Assistant API
api:

sensor:
  - platform: mhz19
    uart_id: uart_1
    co2:
      name: "$devicename CO2 Value"
      state_class: "measurement"
    #temperature:
    #  name: "MH-Z19 Temperature"
    #  state_class: "measurement"
    update_interval: 60s
    automatic_baseline_calibration: false
    
  - platform: pmsx003
    type: PMSX003
    uart_id: uart_2
    
    pm_1_0:
      name: "$devicename Particulate Matter <1.0µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      filters:
        - throttle: 60s
    pm_2_5:
      name: "$devicename Particulate Matter <2.5µm Concentration"
      icon: "mdi:weather-fog"
      state_class: "measurement"
      filters:
        - throttle: 60s      
    pm_10_0:
      name: "$devicename Particulate Matter <10.0µm Concentration"  
      icon: "mdi:weather-fog"
      state_class: "measurement"
      filters:
        - throttle: 60s   
  - platform: bme280
    temperature:
      name: "$devicename Temperature"
      state_class: "measurement"
      oversampling: 16x
      accuracy_decimals: 2
    pressure:
      name: "$devicename Pressure"
      state_class: "measurement"
      accuracy_decimals: 2
    humidity:
      name: "$devicename Humidity"
      state_class: "measurement"
      accuracy_decimals: 2
    address: 0x76
    update_interval: 60s  
  - platform: bh1750
    name: "$devicename Illuminance"
    state_class: "measurement"
    address: 0x23
    measurement_duration: 69
    update_interval: 60s    

binary_sensor:
  - platform: gpio
    pin: 21
    name: "$devicename Motion"
    device_class: motion    
    filters:
        - delayed_off: 60s     
interval:
  - interval: 60s
    then:
      - switch.turn_on: pms_set
      - delay: 20s
      - switch.turn_off: pms_set  
